/*
 	Default DDL file using sqlite
 */
CREATE TABLE IF NOT EXISTS EXECUTION
(
  EXECUTION_ID     INTEGER PRIMARY KEY AUTOINCREMENT,
  START_TIME       TIMESTAMP,
  END_TIME         TIMESTAMP,
  STATUS		   STRING
)!!
CREATE TABLE IF NOT EXISTS PROCESSING_URL
(
  PROCESSING_URL_ID  INTEGER PRIMARY KEY AUTOINCREMENT,
  EXECUTION_ID       BIGINT              NOT NULL,
  URL				 STRING,
  HTTP_METHOD		 STRING,
  STATUS			 STRING,
  VULNERABLE		 BOOLEAN,
  
  CONSTRAINT FK_PROCESSING_URL_EXECUTION FOREIGN KEY (EXECUTION_ID) REFERENCES EXECUTION (EXECUTION_ID) ON DELETE CASCADE
)!!
CREATE TABLE IF NOT EXISTS TAINTED_PARAMETER
(
  TAINTED_PARAMETER_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
  PROCESSING_URL_ID          BIGINT              NOT NULL,
  PARAMETER_NAME			 STRING,
  IS_INJECTABLE				 BOOLEAN,
  PAYLOAD					 STRING,
  CONSTRAINT FK_INJECTABLE_PARAMETER_PROCESSING_URL FOREIGN KEY (PROCESSING_URL_ID) REFERENCES PROCESSING_URL (PROCESSING_URL_ID) ON DELETE CASCADE
)!!